<?php if (!empty($data)): ?>
    <?php foreach ($data as $key => $value): ?>
        <?php if ($value['prefix'] && $relInfo = $value['relInfo']) : ?>
            <?=rtrim($relInfo, ':').': '?>
        <?php endif; ?>
        <?php if ($id = $value['id']) : ?>
            <a href="<?=$this->recordLink()->getUrl($value['id'])?>">
                <?=$this->escapeHtml($value['title'])?>
            </a>
        <?php else: ?>
            <?=$this->escapeHtml($value['title'])?>
        <?php endif; ?>
        <br />
    <?php endforeach; ?>
<?php endif; ?>