<h2><?=$this->transEsc('email_alert_popup_title')?></h2>
<?php // Display success message if canceling the popup was successful ?>
<?php if ($this->success): ?>
    <div class="alert-success alert"><?=$this->transEsc('email_alert_cancel_success_alert')?></div>
    <p><?=$this->transEsc('email_alert_cancel_success_text_1')?></p>
    <p><?=$this->transEsc('email_alert_cancel_success_text_2')?></p>
<?php // Display error message if canceling the popup was not successful ?>
<?php else: ?>
    <div class="alert-danger alert"><?=$this->transEsc('email_alert_cancel_error_alert')?></div>
    <p><?=$this->transEsc('email_alert_cancel_error_text_1')?></p>
    <p><?=$this->transEsc('email_alert_cancel_error_text_2')?></p>
<?php endif; ?>
<div style="text-align: right;">
    <button class="btn btn-default lightbox-only float-right" data-dismiss="modal"><?=$this->translate('close') ?></button>
</div>