    <div class="container">
        <h2>Über AKsearch / Impressum</h2><br />
        <p>
            <h3>Offenlegung</h3>
            <h4>Medieninhaber, Herausgeber und Eigentümer</h4>
            AK Bibliothek Wien für Sozialwissenschaften<br />
            Prinz-Eugen-Straße 20-22, 1040 Wien, Österreich<br />
            Telefon: NOTHING<br />
            eMail: NOTHING<br />
            <br />
            <h4>Weitere Informationen</h4>
            Zuständige Aufsichtsbehörde: Bundesministerium für Arbeit, Soziales,
            Gesundheit und Konsumentenschutz<br />
            Anwendbare Rechtsvorschriften: Bundesgesetz über die Kammern für Arbeiter
            und Angestellte und die Bundeskammer für Arbeiter und Angestellte
            (Arbeiterkammergesetz 1992 - AKG), BGBL 626/1991<br />
            Vertretungsbefugtes Organ: NOTHING<br />‌
            <br />‌<br />
        </p>
        <p>
            <h3>Icon Lizenzen</h3>
            Untenstehende Icons werden in AKsearch verwendet. Überaus dankbar wurden
            sie vom &#039;Noun Project&#039; (https://thenounproject.com/)
            übernommen. Vielen Dank an all die kreativen Köpfe, die ihre Arbeit mit
            anderen teilen. Alle Icons stehen unter der Lizenz CC BY 3.0
            (https://creativecommons.org/licenses/by/3.0/). Alle Icons wurden leicht
            verändert (hauptsächlich in Größe und Farbe).<br />
            <br />
            <ul>
                <li><a href="https://thenounproject.com/icon/70094/" target="new">article</a> by Dmitry Podluzny from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/108321/" target="new">audiobook</a> by Creative Stall from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/353763/" target="new">Book</a> by To Uyen from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/137857/" target="new">books</a> by Jakub Čaja from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/2301/" target="new">Braille</a> by Jakob Vogel from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/329990/" target="new">Clapperboard</a> by lastspark from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/166097/" target="new">Compact Disc</a> by Jamison Wieser from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/166093/" target="new">DVD</a> by Jamison Wieser from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/253541/" target="new">ebook</a> by Vectors Market from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/16250/" target="new">Film</a> by José Campos from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/575708/" target="new">Headphones</a> by Kevin from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/102049/" target="new">Help Document</a> by Muneer A.Safiah from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/91481/" target="new">html</a> by Konstantin Velichko from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/11528/" target="new">Knight</a> by Christopher T. Howlett from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/75077/" target="new">magazine</a> by Glenis Gómez Rios from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/26944/" target="new">Map</a> by Juan Pablo Bravo from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/1565/" target="new">Media</a> by Thibault Geffroy from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/145152/" target="new">Music Note</a> by Creative Stall from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/62502/" target="new">Newspaper</a> by Konrad Michalik from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/541/" target="new">Picture</a> by Edward Boatman from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/19817/" target="new">Poster</a> by irene hoffman from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/36568/" target="new">quill</a> by Mister Pixel from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/18924/" target="new">Speaker</a> by Icomatic from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/1128220/" target="new">vhs</a> by Creaticca Creative Agency from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
                <li><a href="https://thenounproject.com/icon/36452/" target="new">video-support</a> by Vicons Design from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            </ul>
            <br />
        </p>
        <!--
        <p>
            <h3>Cookie consent Lizenz</h3>
            <p>Der Code für das Cookie Consent Popup kommt von Silktide Ltd. Dieses Unternehmen stellt den Code frei und Open Source unter der MIT Lizenz (https://opensource.org/licenses/MIT) auf https://cookieconsent.insites.com/ zur Verfügung. Wir danken vielmals.</p><br />
        </p>
        -->
        <p>
            <h3>Metadaten Lizenzen</h3>
            <p>Die Metadaten des Directory of Open Acces Journals
            (DOAJ - https://doaj.org/), die in AKsearch indexiert sind und somit
            durchsucht werden können, werden unter der Lizenz CC BY-SA 4.0
            (https://creativecommons.org/licenses/by-sa/4.0/) zur Verfügung gestellt.
            Die Metadaten aus anderen Quellen sind entweder völlig frei verfügbar
            oder werden mit Zustimmung des Rechteinhabers verwendet.</p>
            <br />
        </p>
    </div>