<?php
    // Set up page title:
    $this->headTitle($this->translate('welcome'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li class="active"><a href="' . $this->url('content-page', ['page' => 'welcome']) . '">' . $this->transEsc('welcome') . '</a></li>';
?>

<div class="container">
    <h2>Willkommen bei der AK Bibliothek Wien für Sozialwissenschaften</h2>
    
    <div class="flash-message alert alert-success">Ihre Registrierung war erfolgreich!</div>

    <p>
    Sie erhalten in Kürze eine E-Mail mit weiteren Informationen. Sollten Sie dieses
    E-Mail nicht erhalten, sehen Sie bitte auch im Spam-Ordner Ihres E-Mail-Kontos
    nach.
    <br /><br />
    Mit den erhaltenen Zugangsdaten können Sie sich an Ihrem Bibliothekskonto
    anmelden und die Services der AK Bibliothek Wien nutzen.
    <br /><br />
    Wir wünschen Ihnen viel Freude damit,
    <br />
    Ihr Bibliotheksteam
    <br /><br /><br /><br /><br />
    </p>
</div>