<?php
  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $config = $this->config()->get('config');
    $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
  }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
    $searchHome = $options->getSearchHomeAction();
    $advSearch = $options->getAdvancedSearchAction();
    $lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
    $lastLimit = $this->searchMemory()->getLastLimit($this->searchClassId);
    $ignoreHiddenFilterMemory = $this->ignoreHiddenFilterMemory ?? false;
    $ignoreHiddenFiltersInRequest = $this->ignoreHiddenFiltersInRequest ?? false;
    $hiddenFilters = $this->searchTabs()->getHiddenFilters($this->searchClassId, $ignoreHiddenFilterMemory, $ignoreHiddenFiltersInRequest);
    if (empty($hiddenFilters) && !$ignoreHiddenFilterMemory) {
        $hiddenFilters = $this->searchMemory()->getLastHiddenFilters($this->searchClassId);
        if (empty($hiddenFilters)) {
            $hiddenFilters = $this->searchTabs()->getHiddenFilters($this->searchClassId);
        }
    }
    $hiddenFilterParams = $this->searchTabs()->getCurrentHiddenFilterParams($this->searchClassId, $ignoreHiddenFilterMemory, '?');

    // AK: Get handlers for active search tab
    $searchTypeForTabConfig = ($this->searchType == 'advanced_searchform') ? 'advanced' : $this->searchType; // AK: Handle special case "advanced_searchform" for showing tabs on the advances search form screen
    $tabConfig = $this->searchTabs()->getTabConfig($this->searchClassId, $this->lookfor, $this->searchIndex, $searchTypeForTabConfig, $hiddenFilters);
    $handlers = $this->searchbox()->getHandlers(
      $this->searchClassId, $this->searchIndex ?? null, $tabConfig['selected'] ?? null
    );
    $handlerCount = count($handlers);

    if (!isset($this->filterList) || !isset($this->checkboxFilters)) {
        $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
        $filterList = $params->getFilterList(true);
        $checkboxFilters = $params->getCheckboxFacets();
    } else {
        $filterList = is_array($this->filterList) ? $this->filterList : [];
        $checkboxFilters = is_array($this->checkboxFilters) ? $this->checkboxFilters : [];
    }
    $filterDetails = $this->searchbox()->getFilterDetails($filterList, $checkboxFilters);
    $showFilters = $filterDetails && (isset($results) || $options->getRetainFilterSetting());
?>

<?php if ($this->searchType == 'advanced'): ?>
  <div class="navbar-form navbar-left flip">
    <?php $tabs = $this->context($this)->renderInContext('search/searchTabs', ['searchTabs' => $tabConfig['tabs']]); ?>
    <?php if (!empty($tabs)): ?><?=$tabs ?><div class="tab-content clearfix"><?php endif; ?>
      <p class="adv_search_terms"><?=$this->transEsc("Your search terms")?>: "<strong><?=$this->escapeHtml($this->lookfor)?></strong>"</p>
      <p class="adv_search_links">
        <?php // AK: Add hidden filters on link to edit advanced search when we have search tabs ?>
        <?php if (!empty($tabs)): ?>
          <a href="<?=$this->url($advSearch)?><?=(!empty($hiddenFilterParams)) ? $hiddenFilterParams.'&edit='.$this->escapeHtmlAttr($this->searchId) : '?edit='.$this->escapeHtmlAttr($this->searchId)?>"><?=$this->transEsc("Edit this Advanced Search")?></a> |
        <?php else: ?>
          <a href="<?=$this->url($advSearch)?>?edit=<?=$this->escapeHtmlAttr($this->searchId)?>"><?=$this->transEsc("Edit this Advanced Search")?></a> |
        <?php endif; ?>
        <a href="<?=$this->url($advSearch) . $hiddenFilterParams?>"><?=$this->transEsc("Start a new Advanced Search")?></a> |
        <a href="<?=$this->url($searchHome) . $hiddenFilterParams?>"><?=$this->transEsc("Start a new Basic Search")?></a>
      </p>
      <?=$this->context($this)->renderInContext(
        'search/filters.phtml',
        [
          'params' => $params ?? null,
          'urlQuery' => isset($results) ? $results->getUrlQuery() : null,
          'filterList' => $showFilters ? $filterList : [],
          'checkboxFilters' => $showFilters ? $checkboxFilters : [],
          'searchClassId' => $this->searchClassId,
          'searchType' => $this->searchType,
        ]
      );?>
    <?php if (!empty($tabs)): ?></div><?php endif; ?>
  </div>
<?php elseif ($this->searchType == 'advanced_searchform'): ?>
  <?php // AK: Special layout for advanced search form screen when search tabs are activated. We only show tabs without any other information.
  // The searchType "advanced_searchform" comes from search/advanced/layout.phtml ?>
  <div class="navbar-form navbar-left flip advanced-searchform-tabs">
    <?php $tabs = $this->context($this)->renderInContext('search/searchTabs', ['searchTabs' => $tabConfig['tabs']]); ?>
    <?php if (!empty($tabs)): ?><?=$tabs?><?php endif; ?>
  </div>
<?php else: ?>
  <form id="searchForm" class="searchForm navbar-form navbar-left flip" method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" autocomplete="off">
    <?= $this->context($this)->renderInContext('search/searchTabs', ['searchTabs' => $tabConfig['tabs']]); ?>
    <?php $placeholder = $this->searchbox()->getPlaceholderText($tabConfig['selected']['id'] ?? null); ?>
    <?php // AK: Add some wrappers that are necessary for the "X" clearer button and for better styling on mobile devices ?>
    <div id="searchForm_options_wrapper">
      <div id="searchForm_lookfor_wrapper">
        <input id="searchForm_lookfor" class="searchForm_lookfor form-control search-query<?php if($this->searchbox()->autocompleteEnabled($this->searchClassId)):?> autocomplete searcher:<?=$this->escapeHtmlAttr($this->searchClassId) ?><?=$this->searchbox()->autocompleteAutoSubmit($this->searchClassId) ? ' ac-auto-submit' : '' ?><?php endif ?>" type="text" name="lookfor" value="<?=$this->escapeHtmlAttr($this->lookfor)?>"<?php if ($placeholder): ?> placeholder="<?=$this->transEscAttr($placeholder) ?>"<?php endif ?> aria-label="<?=$this->transEscAttr("search_terms")?>" />
        <?php // AK: Add "X" button in seaerchbox for clearing it ?>
        <i id="searchForm_lookfor_clear" class="fa fa-times-circle fa-2x" aria-hidden="true"></i>
      </div>
      <?php if ($handlerCount > 1): ?>
        <select id="searchForm_type" class="searchForm_type form-control" name="type" data-native-menu="false" aria-label="<?=$this->transEscAttr("Search type")?>">
          <?php $currentGroup = $insideGroup = false; ?>
          <?php foreach ($handlers as $handler): ?>
            <?php
              // AK: Setting indent to "false" so that we don't have two extra dashes ("--") before the DropDown options
              $handler['indent'] = false;
              if ($currentGroup !== ($handler['group'] ?? false)) {
                $currentGroup = $handler['group'];
                if ($insideGroup) {
                  echo '</optgroup>';
                }
                if ($currentGroup) {
                  echo '<optgroup label="' . $this->escapeHtmlAttr($currentGroup) . '">';
                  $insideGroup = true;
                } else {
                  $insideGroup = false;
                }
              }
            ?>
            <option value="<?=$this->escapeHtmlAttr($handler['value'])?>"<?=$handler['selected'] ? ' selected="selected"' : ''?>><?=$handler['indent'] ? '-- ' : ''?><?=$this->transEsc($handler['label'])?></option>
          <?php endforeach; ?>
          <?php if ($insideGroup): ?>
            </optgroup>
          <?php endif; ?>
        </select>
      <?php elseif ($handlerCount == 1): ?>
        <input type="hidden" name="type" value="<?=$this->escapeHtmlAttr($handlers[0]['value'])?>" />
      <?php endif; ?>
    </div>
    <?php // AK: Add wrapper for better styling on mobile devices ?>
    <div id="searchForm_execute_wrapper">
      <button type="submit" class="btn btn-primary"><i class="fa fa-search" aria-hidden="true"></i>
      <?php
        // AK: Remove text from search button by commenting out the following line
        // echo $this->transEsc("Find");
        ?>
      </button>
      <?php if ($advSearch): ?>
        <?php // AK: Add hidden filters on link to advanced search when we have search tabs ?>
        <?php
        // Default link to advanced search
        $advSearchLink = $this->url($advSearch) . (($this->searchId ?? false) ? '?edit=' . $this->escapeHtmlAttr($this->searchId) : $hiddenFilterParams);
        if (!empty($tabConfig['tabs'])) {
          // If tabs are configured, add the hidden filters to it
          $advSearchLink = $this->url($advSearch) . (($this->searchId ?? false) ? $hiddenFilterParams . '&edit=' . $this->escapeHtmlAttr($this->searchId) : $hiddenFilterParams);
        }
        ?>
        <a href="<?=$advSearchLink?>" class="btn btn-link" rel="nofollow"><?=$this->transEsc("Advanced")?></a>
      <?php endif; ?>
      <?php if ($geoUrl = $this->geocoords()->getSearchUrl($options)) : ?>
          <a href="<?=$geoUrl ?>" class="btn btn-link"><?=$this->transEsc('Geographic Search')?></a>
      <?php endif; ?>

      <?php $shards = $options->getShards(); if ($options->showShardCheckboxes() && !empty($shards)): ?>
        <?php
        $selectedShards = $this->selectedShards ?? $options->getDefaultSelectedShards();
        ?>
        <br />
        <?php foreach ($shards as $shard => $val): ?>
          <?php $isSelected = empty($selectedShards) || in_array($shard, $selectedShards); ?>
            <input type="checkbox" <?=$isSelected ? 'checked="checked" ' : ''?>name="shard[]" value='<?=$this->escapeHtmlAttr($shard)?>' /> <?=$this->transEsc($shard)?>
        <?php endforeach; ?>
      <?php endif; ?>
    </div>

    <?php if (($hasDefaultsApplied ?? false) || !empty($filterDetails)): ?>
      <?php if ($options->getRetainFilterSetting()): ?>
        <?php foreach ($filterDetails as $current): ?>
          <input class="applied-filter" id="<?=$this->escapeHtmlAttr($current['id'])?>" type="hidden" name="filter[]" value="<?=$this->escapeHtmlAttr($current['value'])?>" />
        <?php endforeach; ?>
        <?php if ($hasDefaultsApplied ?? false): ?>
          <input class="applied-filter" id="dfApplied" type="hidden" name="dfApplied" value="1" />
        <?php endif; ?>
      <?php endif; ?>
    <?php endif; ?>
    <?php foreach ($hiddenFilters as $key => $filter): ?>
      <?php foreach ($filter as $value): ?>
        <input type="hidden" name="hiddenFilters[]" value="<?=$this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr($value)?>" />
      <?php endforeach; ?>
    <?php endforeach; ?>
    <?php
      /* Show hidden field for active search class when in combined handler mode. */
      if ($this->searchbox()->combinedHandlersActive()) {
        echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '" />';
      }
      /* Load hidden limit preference from Session */
      if (!empty($lastLimit)) {
        echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '" />';
      }
      if (!empty($lastSort)) {
        echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '" />';
      }
    ?>
    <?=$this->context($this)->renderInContext(
      'search/filters.phtml',
      [
        'params' => $params ?? null,
        'urlQuery' => isset($results) ? $results->getUrlQuery() : null,
        'filterList' => $showFilters ? $filterList : [],
        'checkboxFilters' => $showFilters ? $checkboxFilters : [],
        'searchClassId' => $this->searchClassId,
        'searchType' => $this->searchType,
      ]
    );?>
  </form>
<?php endif; ?>

<?php
  // AK: Append the JS that clears the search box when clicking on the "X"
  echo $this->inlineScript()->appendFile('clearSearchbox.js');
?>
