<?php
    // Set page title.
    $this->headTitle($this->translate('auto_configure_title'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('install-home') . '">' . $this->transEsc('auto_configure_title') . '</a></li> <li class="active">' . $this->transEsc('Fix Database') . '</li>';
?>
<h2><?=$this->transEsc('auto_configure_title')?></h2>

<?=$this->flashmessages()?>

<?php // AK: Check if form for editing the table should be shown ?>
<?php if ($this->showForm): ?>
    <p>Sending this form adds the column "show_email_alert_popup" to the user table for indicating if a user wants to show or hide the popup. The column value defaults to "1" for "true".</p>
    <form class="form-fix-loanhistorytable" method="post">
        <div class="form-group">
            <label class="control-label" for="dbrootuser">MySQL Root User:</label>
            <input type="text" name="dbrootuser" id="dbrootuser" value="<?=$this->escapeHtmlAttr($this->dbrootuser)?>" class="form-control" required/>
        </div>
        <div class="form-group">
            <label class="control-label" for="dbrootpass">MySQL Root Password:</label>
            <input type="password" name="dbrootpass" id="dbrootpass" value="" class="form-control" required/>
    </div>
        <div class="form-group">
            <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Submit') ?>" />
        </div>
    </form>
<?php endif; ?>