<footer class="hidden-print">
  <div class="footer-container">
    <div class="footer-column">
      <?php $this->slot('footer-left')->start(); ?>
        <p><strong><?=$this->transEsc('Search Options')?></strong></p>
        <ul>
          <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
          <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
        </ul>
      <?=$this->slot('footer-left')->end(); ?>
    </div>
    <div class="footer-column">
      <?php $this->slot('footer-center')->start(); ?>
        <p><strong><?=$this->transEsc('Find More')?></strong></p>
        <ul>
          <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
          <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
          <?php // AK: Removing "Channel Explore" and "Course Reserve" links ?>
          <?php /* <li><a href="<?=$this->url('channels-home')?>"><?=$this->transEsc('channel_explore')?></a></li>
          <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li> */ ?>
          <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>
          <?php // AK: Open the "email alert popup" if, but display the link only if configured to do so. ?>
          <?php $accountConf = $this->emailalertpopup()->getConfig(); ?>
          <?php if (($accountConf['schedule_searches'] ?? false) && ($accountConf['scheduled_search_popup'] ?? false)): ?>
            <li><a href="<?=$this->url('emailalert-processor')?>" data-lightbox><?=$this->transEsc('email_alert')?></a></li>
          <?php endif; ?>
        </ul>
      <?=$this->slot('footer-center')->end(); ?>
    </div>
    <div class="footer-column">
      <?php $this->slot('footer-right')->start(); ?>
        <p><strong><?=$this->transEsc('Need Help?')?></strong></p>
        <ul>
          <li><a href="<?=$this->url('help-home')?>?topic=search&amp;_=<?=time() ?>" data-lightbox class="help-link"><?=$this->transEsc('Search Tips')?></a></li>
          <?php // AK: Linking to custom content pages ?>
          <li><a href="<?=$this->url('content-page', ['page' => 'about']) ?>"><?=$this->transEsc('about')?></a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'privacy']) ?>"><?=$this->transEsc('privacy_statement')?></a></li>
          <?php // AK: Linking to library website ?>
          <li><a href="https://wien.arbeiterkammer.at/service/bibliothek" target="_blank">AK Bibliothek Wien</a></li>
        </ul>
      <?=$this->slot('footer-right')->end(); ?>
    </div>
  </div>
  <div class="poweredby">
    <?=$this->layout()->poweredBy ?>
  </div>
</footer>
